version: '3.9'
networks:
  chica:

services:
  chica:
    image: chica
    build:
      dockerfile: Dockerfile
    networks:
      - chica
    restart: unless-stopped
    container_name: chica_prod


